site_name: Stone Data Challenge
theme:
  palette:
    primary: green
    accent: green
  name: material
  font:
    text: Roboto
  features:
    - content.code.annotate
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
plugins:
  - search
  - mermaid2
nav:
  - Framework de Avaliação: "index.md"
  - Dicionário de Dados: "data_dict.md"
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tablesort.js